### ISSUE TITLE
How long does it take to update the list of newly uploaded files in the database?

### ISSUE THREAD

**Issue by Richman881** [KiKiHUN1/Mega-Schematics-Downloader#1]
How long does it take to update the list of newly uploaded files in the database? I uploaded a file and clicked the Refresh button on the client, but cannot search for it. I am using the Windows client. Do you update schematic files on a long term basis?

**Comment by Richman881** [comment]
By the way, ,,,, Is an amazing project!

**Comment by KiKiHUN1** [comment]
Thank you for the contribution.
I add them manually to prevent spamming.
