### ISSUE TITLE
Multiple Antivirus report Trojan

### ISSUE THREAD

**Issue by HKEB** [KiKiHUN1/Mega-Schematics-Downloader#2]
https://www.virustotal.com/gui/file/84cc198f0f08febb881ec05967177d23c57371ea151d979635fe77f4e1f0542b

Number increasing, last time I checked it were 19, now there are 21.

**Comment by KiKiHUN1** [comment]
Next time please read the details tab too and the manual.
Not signed executables will fail some low budget  antivirus checks.
![Screenshot_20240215_154027_Chrome](https://github.com/KiKiHUN1/Mega-Schematics-Downloader/assets/71247943/3a30cf85-f87a-44d9-ab22-0024708e2d05)
