### ISSUE TITLE
Status is ready but refresh button is disabled

### ISSUE THREAD

**Issue by adidaus** [KiKiHUN1/Mega-Schematics-Downloader#3]
happen often
windows 10
![image](https://github.com/KiKiHUN1/Mega-Schematics-Downloader/assets/25550666/c3e18444-1490-436d-b1c3-4b74cca0182f)

**Comment by KiKiHUN1** [comment]
Can you write a step by step guide to achieve this state?

**Comment by adidaus** [comment]
I just open it, 
now i'm on new machine with windows tiny10, the program doesn't even open

**Comment by KiKiHUN1** [comment]
.net is needed for this app to run. tiny10 and 11 removed every windows update part that would give you a popup to install the .net and others that is needed for apps.

**Comment by KiKiHUN1** [comment]
btw check out the new verbosederrors executable. It shouls catch every error that is present.
