### ISSUE TITLE
[Bug] It says there is no folder and nothing appear to download.

### ISSUE THREAD

**Issue by Pillowmaster69** [KiKiHUN1/Mega-Schematics-Downloader#4]
**File name**
-

**Current folder tree**
-

**Correct folder tree**
-

**Additional context**
-

**Comment by KiKiHUN1** [comment]
It should create a folder next to the executable. Plese try running the executable in the c:\ or any other drive root directory to eliminate any speacial characters.

**Comment by Pillowmaster69** [comment]
Thank you, it solve every problem

**Comment by KiKiHUN1** [comment]
I'm glad to help.
